<a href="https://colab.research.google.com/github/2003DEE/DEEPAK_FMML/blob/main/Revenue.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
!wget "https://raw.githubusercontent.com/2003DEE/DEEPAK_FMML/main/dataRevenue%20-%20Sheet1.csv"

--2023-07-12 05:30:10--  https://raw.githubusercontent.com/2003DEE/DEEPAK_FMML/main/dataRevenue%20-%20Sheet1.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1023588 (1000K) [text/plain]
Saving to: ‘dataRevenue - Sheet1.csv.1’

dataRevenue - Sheet 100%[===================>] 999.60K  --.-KB/s    in 0.03s

2023-07-12 05:30:11 (31.0 MB/s) - ‘dataRevenue - Sheet1.csv.1’ saved [1023588/1023588]

In [ ]:
data=pd.read_csv('dataRevenue - Sheet1.csv')
data.head()

,Line Id,Date,Name,AFC Revenue (A),Travel Revenue (B),Famoco Revenue (C),QR Online Revenue (D),QR Paper Revenue (E),Static QR Revenue (E1),Whats App QR Revenue (E2),...,Total Exit Count (Q) = O + P,Ridership Count,CSC Qty (R),CST Qty (S),P-CSC (1-day) Qty (T),P-CSC (30-day) Qty (U),Paper Ticket Qty (V),QR Online Qty (W),QR Paper Qty (X),Total Qty (Y) = R + S + T + U + V + W + X
0,1,22/07/2022,01ED-Wimco Nagar Depot Metro,61002,62720,0,1504,19080,0,0,...,1621,1366,21,13,0,0,9,40,472,555
1,1,22/07/2022,01EF-Wimco Nagar Metro,111334,128017,0,3048,32660,0,0,...,3691,2992,40,103,3,0,5,89,797,1037
2,1,22/07/2022,01F1-Thiruvotriyur Metro,89301,93957,0,1288,20820,0,0,...,2942,2480,46,0,0,0,3,41,552,642
3,1,22/07/2022,01F3-Thiruvotriyur Theradi Metro,93300,116431,0,1880,31170,0,0,...,3783,2928,36,91,4,0,7,52,838,1028
4,1,22/07/2022,01F5-Kaladipet Metro,88875,90045,0,1000,21120,0,0,...,3170,2597,11,0,1,0,1,33,612,658

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6724 entries, 0 to 6723
Data columns (total 32 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Line Id                                      6724 non-null   int64
 1   Date                                         6724 non-null   object
 2   Name                                         6724 non-null   object
 3   AFC Revenue (A)                              6724 non-null   int64
 4   Travel Revenue (B)                           6724 non-null   int64
 5   Famoco Revenue (C)                           6724 non-null   int64
 6   QR Online Revenue (D)                        6724 non-null   int64
 7   QR Paper Revenue (E)                         6724 non-null   int64
 8   Static QR Revenue (E1)                       6724 non-null   int64
 9   Whats App QR Revenue (E2)                    6724 non-null   int64
 10  Total Revenue (F) = A + C + D + E + E1 + E2  6724 non-null   int64
 11  Parked Vehicle - Cash Revenue (F)            6724 non-null   int64
 12  Parked Vehicle - Card Revenue (G)            6724 non-null   int64
 13  Parked Vehicle - Total Revenue (H) = F + G   6724 non-null   int64
 14  Pass Sale - Cash Revenue (I)                 6724 non-null   int64
 15  Pass Sale - Card Revenue (J)                 6724 non-null   int64
 16  Pass Sale - Total Revenue (K) = I + J        6724 non-null   int64
 17  CL Entry Count (L)                           6724 non-null   int64
 18  QR Entry Count (M)                           6724 non-null   int64
 19  Total Entry Count (N) = L + M                6724 non-null   int64
 20  CL Exit Count (O)                            6724 non-null   int64
 21  QR Exit Count (P)                            6724 non-null   int64
 22  Total Exit Count (Q) = O + P                 6724 non-null   int64
 23  Ridership Count                              6724 non-null   int64
 24  CSC Qty (R)                                  6724 non-null   int64
 25  CST Qty (S)                                  6724 non-null   int64
 26  P-CSC (1-day) Qty (T)                        6724 non-null   int64
 27  P-CSC (30-day) Qty (U)                       6724 non-null   int64
 28  Paper Ticket Qty (V)                         6724 non-null   int64
 29  QR Online Qty (W)                            6724 non-null   int64
 30  QR Paper Qty (X)                             6724 non-null   int64
 31  Total Qty (Y) = R + S + T + U + V + W + X    6724 non-null   int64
dtypes: int64(30), object(2)
memory usage: 1.6+ MB

In [ ]:
data['Date'] = pd.to_datetime(data['Date'], format = "%d/%m/%Y")

In [ ]:
day=[]
for obj in data['Date']:
  day.append(obj.day_name())
print(day)
data['Day']=pd.DataFrame(day)

['Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Friday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 

In [ ]:
data

,Line Id,Date,Name,AFC Revenue (A),Travel Revenue (B),Famoco Revenue (C),QR Online Revenue (D),QR Paper Revenue (E),Static QR Revenue (E1),Whats App QR Revenue (E2),...,Ridership Count,CSC Qty (R),CST Qty (S),P-CSC (1-day) Qty (T),P-CSC (30-day) Qty (U),Paper Ticket Qty (V),QR Online Qty (W),QR Paper Qty (X),Total Qty (Y) = R + S + T + U + V + W + X,Day
0,1,2022-07-22,01ED-Wimco Nagar Depot Metro,61002,62720,0,1504,19080,0,0,...,1366,21,13,0,0,9,40,472,555,Friday
1,1,2022-07-22,01EF-Wimco Nagar Metro,111334,128017,0,3048,32660,0,0,...,2992,40,103,3,0,5,89,797,1037,Friday
2,1,2022-07-22,01F1-Thiruvotriyur Metro,89301,93957,0,1288,20820,0,0,...,2480,46,0,0,0,3,41,552,642,Friday
3,1,2022-07-22,01F3-Thiruvotriyur Theradi Metro,93300,116431,0,1880,31170,0,0,...,2928,36,91,4,0,7,52,838,1028,Friday
4,1,2022-07-22,01F5-Kaladipet Metro,88875,90045,0,1000,21120,0,0,...,2597,11,0,1,0,1,33,612,658,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6719,2,2022-12-31,0225-Vadapalani,122104,286251,300,13848,140794,0,0,...,5605,41,921,9,0,31,520,4463,5985,Saturday
6720,2,2022-12-31,0227-Ashok Nagar,91451,141358,460,4624,62388,0,0,...,3106,45,399,4,0,7,214,2063,2732,Saturday
6721,2,2022-12-31,0229-Ekkattuthangal,113435,88658,1000,2896,34884,0,0,...,2182,71,237,7,0,5,121,1102,1543,Saturday
6722,2,2022-12-31,0231-Arignar Anna Alandur,126775,202940,0,7392,88180,0,0,...,4289,44,744,14,0,11,264,2580,3657,Saturday
6723,2,2022-12-31,0233-St. Thomas Mount,69346,126379,200,6152,65394,0,0,...,2308,21,249,5,0,7,219,1909,2410,Saturday

In [ ]:
data.columns

Index(['Line Id', 'Date', 'Name', 'AFC Revenue (A)', 'Travel Revenue (B)',
       'Famoco Revenue (C)', 'QR Online Revenue (D)', 'QR Paper Revenue (E)',
       'Static QR Revenue (E1)', 'Whats App QR Revenue (E2)',
       'Total Revenue (F) = A + C + D + E + E1 + E2',
       'Parked Vehicle - Cash Revenue (F)',
       'Parked Vehicle - Card Revenue (G)',
       'Parked Vehicle - Total Revenue (H) = F + G',
       'Pass Sale - Cash Revenue (I)', 'Pass Sale - Card Revenue (J)',
       'Pass Sale - Total Revenue (K) = I + J', 'CL Entry Count (L)',
       'QR Entry Count (M)', 'Total Entry Count (N) = L + M',
       'CL Exit Count (O)', 'QR Exit Count (P)',
       'Total Exit Count (Q) = O + P', 'Ridership Count', 'CSC Qty (R)',
       'CST Qty (S)', 'P-CSC (1-day) Qty (T)', 'P-CSC (30-day) Qty (U)',
       'Paper Ticket Qty (V)', 'QR Online Qty (W)', 'QR Paper Qty (X)',
       'Total Qty (Y) = R + S + T + U + V + W + X', 'Day'],
      dtype='object')

In [ ]:
dat1=data[['Line Id','Day','Date','Name','Total Revenue (F) = A + C + D + E + E1 + E2']].copy()
dat1['year']=dat1['Date'].dt.year
dat1['month']=dat1['Date'].dt.month
dat1['dayno']=dat1['Date'].dt.day

In [ ]:
dat2=dat1.drop(['Date'],axis=1)
dat2

,Line Id,Day,Name,Total Revenue (F) = A + C + D + E + E1 + E2,year,month,dayno
0,1,Friday,01ED-Wimco Nagar Depot Metro,81586,2022,7,22
1,1,Friday,01EF-Wimco Nagar Metro,147042,2022,7,22
2,1,Friday,01F1-Thiruvotriyur Metro,111409,2022,7,22
3,1,Friday,01F3-Thiruvotriyur Theradi Metro,126350,2022,7,22
4,1,Friday,01F5-Kaladipet Metro,110995,2022,7,22
...,...,...,...,...,...,...,...
6719,2,Saturday,0225-Vadapalani,277046,2022,12,31
6720,2,Saturday,0227-Ashok Nagar,158923,2022,12,31
6721,2,Saturday,0229-Ekkattuthangal,152215,2022,12,31
6722,2,Saturday,0231-Arignar Anna Alandur,222347,2022,12,31
6723,2,Saturday,0233-St. Thomas Mount,141092,2022,12,31

In [ ]:
dat2.rename(columns = {'Total Revenue (F) = A + C + D + E + E1 + E2':'Revenue'}, inplace = True)

In [ ]:
print(dat2[dat2['Revenue']==dat2['Revenue'].min()])

      Line Id     Day                   Name  Revenue  year  month  dayno
3875        1  Monday  0129-Nanganallur Road    16207  2022     10     24

In [ ]:
d = dat2.groupby('Name')

In [ ]:
sd=d.get_group('01ED-Wimco Nagar Depot Metro')
sd

,Line Id,Day,Name,Revenue,year,month,dayno
0,1,Friday,01ED-Wimco Nagar Depot Metro,81586,2022,7,22
41,1,Saturday,01ED-Wimco Nagar Depot Metro,80016,2022,7,23
82,1,Sunday,01ED-Wimco Nagar Depot Metro,57438,2022,7,24
123,1,Monday,01ED-Wimco Nagar Depot Metro,90256,2022,7,25
164,1,Tuesday,01ED-Wimco Nagar Depot Metro,94476,2022,7,26
...,...,...,...,...,...,...,...
6519,1,Tuesday,01ED-Wimco Nagar Depot Metro,111907,2022,12,27
6560,1,Wednesday,01ED-Wimco Nagar Depot Metro,120839,2022,12,28
6601,1,Thursday,01ED-Wimco Nagar Depot Metro,112391,2022,12,29
6642,1,Friday,01ED-Wimco Nagar Depot Metro,112571,2022,12,30
6683,1,Saturday,01ED-Wimco Nagar Depot Metro,120911,2022,12,31

In [ ]:
dummy=pd.get_dummies(dat2.Name)
dummy
dam=pd.get_dummies(dat2.Day)
dam

      Friday  Monday  Saturday  Sunday  Thursday  Tuesday  Wednesday
0          1       0         0       0         0        0          0
1          1       0         0       0         0        0          0
2          1       0         0       0         0        0          0
3          1       0         0       0         0        0          0
4          1       0         0       0         0        0          0
...      ...     ...       ...     ...       ...      ...        ...
6719       0       0         1       0         0        0          0
6720       0       0         1       0         0        0          0
6721       0       0         1       0         0        0          0
6722       0       0         1       0         0        0          0
6723       0       0         1       0         0        0          0

[6724 rows x 7 columns]

In [ ]:
dat3=pd.concat([dat2,dummy,dam],axis=1)
dat3

,Line Id,Day,Name,Revenue,year,month,dayno,0101-Washermanpet,0103-Mannadi,0105-High Court,...,0229-Ekkattuthangal,0231-Arignar Anna Alandur,0233-St. Thomas Mount,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday
0,1,Friday,01ED-Wimco Nagar Depot Metro,81586,2022,7,22,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,1,Friday,01EF-Wimco Nagar Metro,147042,2022,7,22,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,1,Friday,01F1-Thiruvotriyur Metro,111409,2022,7,22,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,1,Friday,01F3-Thiruvotriyur Theradi Metro,126350,2022,7,22,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,1,Friday,01F5-Kaladipet Metro,110995,2022,7,22,0,0,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6719,2,Saturday,0225-Vadapalani,277046,2022,12,31,0,0,0,...,0,0,0,0,0,1,0,0,0,0
6720,2,Saturday,0227-Ashok Nagar,158923,2022,12,31,0,0,0,...,0,0,0,0,0,1,0,0,0,0
6721,2,Saturday,0229-Ekkattuthangal,152215,2022,12,31,0,0,0,...,1,0,0,0,0,1,0,0,0,0
6722,2,Saturday,0231-Arignar Anna Alandur,222347,2022,12,31,0,0,0,...,0,1,0,0,0,1,0,0,0,0
6723,2,Saturday,0233-St. Thomas Mount,141092,2022,12,31,0,0,0,...,0,0,1,0,0,1,0,0,0,0

In [ ]:
dat4=dat3.drop(['Day','Name'],axis=1)

In [ ]:
dat4

,Line Id,Revenue,year,month,dayno,0101-Washermanpet,0103-Mannadi,0105-High Court,0109-Government Estate,0111-LIC,...,0229-Ekkattuthangal,0231-Arignar Anna Alandur,0233-St. Thomas Mount,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday
0,1,81586,2022,7,22,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,1,147042,2022,7,22,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,1,111409,2022,7,22,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,1,126350,2022,7,22,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,1,110995,2022,7,22,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6719,2,277046,2022,12,31,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
6720,2,158923,2022,12,31,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
6721,2,152215,2022,12,31,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,0
6722,2,222347,2022,12,31,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
6723,2,141092,2022,12,31,0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0

In [ ]:
y=dat4.Revenue
X=dat4.drop('Revenue',axis=1)

In [ ]:
from sklearn.model_selection import train_test_split,ShuffleSplit,cross_val_score
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=10)

In [ ]:
!pip install lightgbm

Requirement already satisfied: lightgbm in /usr/local/lib/python3.10/dist-packages (3.3.5)
Requirement already satisfied: wheel in /usr/local/lib/python3.10/dist-packages (from lightgbm) (0.40.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from lightgbm) (1.22.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from lightgbm) (1.10.1)
Requirement already satisfied: scikit-learn!=0.22.0 in /usr/local/lib/python3.10/dist-packages (from lightgbm) (1.2.2)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn!=0.22.0->lightgbm) (1.3.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn!=0.22.0->lightgbm) (3.1.0)

In [ ]:
from lightgbm import LGBMRegressor
lr=LGBMRegressor()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9587323592555581

In [ ]:
cv=ShuffleSplit(n_splits=5,test_size=0.2,random_state=10)
cross_val_score(LGBMRegressor(),X,y,cv=cv)

array([0.95873236, 0.95449872, 0.95674115, 0.95992776, 0.95178675])

In [ ]:
X.columns

Index(['Line Id', 'year', 'month', 'dayno', '0101-Washermanpet',
       '0103-Mannadi', '0105-High Court', '0109-Government Estate', '0111-LIC',
       '0113-Thousand Lights', '0115-AG-DMS', '0117-Teynampet',
       '0119-Nandanam', '0121-Saidapet', '0123-Little Mount', '0125-Guindy',
       '0129-Nanganallur Road', '0131-Meenambakkam',
       '0133-Chennai International Airport', '01ED-Wimco Nagar Depot Metro',
       '01EF-Wimco Nagar Metro', '01F1-Thiruvotriyur Metro',
       '01F3-Thiruvotriyur Theradi Metro', '01F5-Kaladipet Metro',
       '01F7-Tollgate Metro', '01F9-New Washermenpet Metro',
       '01FB-Tondiarpet Metro', '01FD-Thiagaraya College Metro',
       '0201-Puratchi Thalaivar Dr. M.G. Ramachandran Central', '0203-Egmore',
       '0205-Nehru Park', '0207-Kilpauk', '0209-Pachaiyappas College',
       '0211-Shenoy Nagar', '0213-Anna Nagar East', '0215-Anna Nagar Tower',
       '0217-Thirumangalam', '0219-Koyambedu',
       '0221-Puratchi Thalaivi Dr. J. Jayalalithaa CMBT', '0223-Arumbakkam',
       '0225-Vadapalani', '0227-Ashok Nagar', '0229-Ekkattuthangal',
       '0231-Arignar Anna Alandur', '0233-St. Thomas Mount', 'Friday',
       'Monday', 'Saturday', 'Sunday', 'Thursday', 'Tuesday', 'Wednesday'],
      dtype='object')

In [ ]:
line1_col=['0101-Washermanpet',
       '0103-Mannadi', '0105-High Court', '0109-Government Estate', '0111-LIC',
       '0113-Thousand Lights', '0115-AG-DMS', '0117-Teynampet',
       '0119-Nandanam', '0121-Saidapet', '0123-Little Mount', '0125-Guindy',
       '0129-Nanganallur Road', '0131-Meenambakkam',
       '0133-Chennai International Airport', '01ED-Wimco Nagar Depot Metro',
       '01EF-Wimco Nagar Metro', '01F1-Thiruvotriyur Metro',
       '01F3-Thiruvotriyur Theradi Metro', '01F5-Kaladipet Metro',
       '01F7-Tollgate Metro', '01F9-New Washermenpet Metro',
       '01FB-Tondiarpet Metro', '01FD-Thiagaraya College Metro']
line2_col=['0201-Puratchi Thalaivar Dr. M.G. Ramachandran Central', '0203-Egmore',
       '0205-Nehru Park', '0207-Kilpauk', '0209-Pachaiyappas College',
       '0211-Shenoy Nagar', '0213-Anna Nagar East', '0215-Anna Nagar Tower',
       '0217-Thirumangalam', '0219-Koyambedu',
       '0221-Puratchi Thalaivi Dr. J. Jayalalithaa CMBT', '0223-Arumbakkam',
       '0225-Vadapalani', '0227-Ashok Nagar', '0229-Ekkattuthangal',
       '0231-Arignar Anna Alandur','0233-St. Thomas Mount']
print(len(line1_col),len(line2_col))

24 17

In [ ]:
def predict_res(Line,year,month,date,station,day):
  sta_id=0
  if Line==1 and station in line1_col:
    sta_id=np.where(X.columns==station)[0][0]
  elif Line==2 and station in line2_col:
    sta_id=np.where(X.columns==station)[0][0]
  else:
    return "Invalid Line_Id or Station_Name"
  day_id=np.where(X.columns==day)[0][0]
  var=np.zeros(len(X.columns))
  var[0]=Line
  var[1]=year
  var[2]=month
  var[3]=date
  if sta_id>=0:var[sta_id]=1
  if day_id>=0:var[day_id]=1
  return lr.predict([var])[0]

In [ ]:
print(predict_res(1,2023,8,4,'0131-Meenambakkam','Friday'))

164420.7993872919

In [ ]:
#!pip install pycaret

In [ ]:
'''
#from pycaret.regression import *

#exp_name = setup(demo,  target = 'Revenue')


#best_model = compare_models()
'''

"\n#from pycaret.regression import *\n\n#exp_name = setup(demo,  target = 'Revenue')\n\n\n#best_model = compare_models()\n"

In [ ]:
import pickle
with open('Revenue_model.pickle','wb') as f:
    pickle.dump(lr,f)

In [ ]:
import json
columns = {
    'data_columns' : [col for col in X.columns]
}
with open("columns.json","w") as f:
    f.write(json.dumps(columns))